import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import "bootstrap/dist/css/bootstrap.css"
import Header from './components/header/header'
import Search from './components/search/search'
import BrandsLogo from './components/brandsLogo'
import Footer from './components/footer/footer'
import style from "./common.module.css"
const inter = Inter({ subsets: ['latin'] })
 
export default function Home() {
  return (
    <>
    <Head>
        <title>LYBLEY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href= "/favicon.ico" />
      </Head>
      <div className={style.bg_image}>
      <Header/>
      <Search/>
      <BrandsLogo/>
      <Footer/>
      </div>
    </>
  )
}
