import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import "bootstrap/dist/css/bootstrap.css"
import Header from './header'
import Search from './search/search'
import BrandsLogo from './brandsLogo'
import Footer from './footer'
import style from "./common.module.css"
import { ToastContainer } from 'react-toastify'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>SPARE TRADE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className='container'>
      <div className=' row d-flex justify-content-center'>
        <div className='col-12 col-md-8'>
         
            <Search />
            <BrandsLogo />
      
        </div>
        </div>
      </div>
      <Footer />
      <ToastContainer />
    </>
  )
}
